// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PragyaPortfolio.Web.Data;

#nullable disable

namespace PragyaPortfolio.Web.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260824185838_AddProjects")]
    partial class AddProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PragyaPortfolio.Web.Models.PortfolioOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Github")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Linkedin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PortfolioOwners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Software developer building applications with C#, ASP.NET Core and AI.",
                            Email = "pragya240119@gmail.com",
                            Github = "https://github.com/pragyaChauhan240119",
                            Linkedin = "https://www.linkedin.com/in/pragya-chauhan-184a9b20a",
                            Name = "Pragya Chauhan"
                        });
                });

            modelBuilder.Entity("PragyaPortfolio.Web.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LiveDemoLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PragyaPortfolio.Web.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Programming",
                            Level = "Intermediate",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Web Development",
                            Level = "Intermediate",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Category = "DevOps",
                            Level = "Intermediate",
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Database",
                            Level = "Intermediate",
                            Name = "Entity Framework Core"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
